apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticketing-sa
  namespace: ticketing
  annotations:
    # Replace <TICKETING_POD_ROLE_ARN> with the output of `terraform output ticketing_pod_role_arn`
    eks.amazonaws.com/role-arn: "arn:aws:iam::808812816838:role/ticketing-prod-pod-role"
