"""
build_single_file.py — Regenerate easymyticket_agent.py from modular source.

Concatenates the 6 agent modules in dependency order, strips cross-module
imports (from agent.X import ...) since all symbols become available inline,
and writes a single self-contained Python file usable as:

    python easymyticket_agent.py [--scan] [--auto]

Run from the EasyMyTicket/agent/ directory:
    python build_single_file.py
"""
import re
import sys
from pathlib import Path

# ─── Module order: each module must come after all modules it depends on ───────
MODULES = [
    "offline_queue.py",
    "diagnostics.py",
    "executor.py",
    "monitor.py",
    "reporter.py",
    "main.py",
]

AGENT_DIR = Path(__file__).parent

# Lines matching these patterns are stripped (they become redundant inline)
_STRIP_PATTERNS = [
    re.compile(r"^from agent\.\w+\s+import\s+"),
    re.compile(r"^import agent\.\w+"),
]

# Module-level docstrings and top-level __name__ guard are kept only from main.py
_DIVIDER = "# " + "─" * 77


def _strip_agent_imports(lines: list[str]) -> list[str]:
    """Remove cross-module agent.* imports."""
    out = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if any(p.match(line) for p in _STRIP_PATTERNS):
            # Skip continuation lines (backslash or open paren)
            if line.rstrip().endswith("("):
                i += 1
                while i < len(lines) and not lines[i].rstrip().endswith(")"):
                    i += 1
                i += 1  # skip closing paren line
            else:
                i += 1
            continue
        out.append(line)
        i += 1
    return out


def build():
    sections = []
    header = (
        '"""\n'
        "EasyMyTicket Desktop Agent — Single-File Edition\n"
        "Auto-generated by build_single_file.py — do not edit directly.\n"
        "Source: EasyMyTicket/agent/{offline_queue,diagnostics,executor,monitor,reporter,main}.py\n"
        "\n"
        "Install: see README or the platform installer scripts.\n"
        "Config via env vars:\n"
        "  AGENT_API_URL      wss://your-backend/\n"
        "  AGENT_API_KEY      emt_xxxx  (get from admin portal)\n"
        "  AGENT_USER_ID      your user ID (e.g. USR001)\n"
        "  AGENT_DEVICE_ID    auto-generated UUID (persisted to disk)\n"
        '"""\n'
    )
    sections.append(header)

    for fname in MODULES:
        path = AGENT_DIR / fname
        if not path.exists():
            print(f"ERROR: {path} not found", file=sys.stderr)
            sys.exit(1)

        raw = path.read_text(encoding="utf-8")
        lines = raw.splitlines(keepends=True)

        # Strip leading module docstring (replaced by the unified header above)
        i = 0
        if lines and lines[0].startswith('"""'):
            i = 1
            while i < len(lines) and '"""' not in lines[i]:
                i += 1
            i += 1  # skip closing triple-quote line
            # Skip blank lines after docstring
            while i < len(lines) and lines[i].strip() == "":
                i += 1
        lines = lines[i:]

        lines = _strip_agent_imports(lines)

        # Remove trailing blank lines
        while lines and lines[-1].strip() == "":
            lines.pop()

        section = f"\n\n{_DIVIDER}\n#  {fname}\n{_DIVIDER}\n\n"
        section += "".join(lines)
        sections.append(section)

    output = "".join(sections) + "\n"

    out_path = AGENT_DIR / "easymyticket_agent.py"
    out_path.write_text(output, encoding="utf-8")
    lines_total = output.count("\n")
    print(f"✓ Written {out_path}  ({lines_total} lines)")


if __name__ == "__main__":
    build()
